[pytest]
filterwarnings =
    ignore:Please use .*python_multipart.*:PendingDeprecationWarning:starlette\.formparsers
    ignore:The 'app' shortcut is now deprecated\.:DeprecationWarning:httpx\._client
